from pathlib import Path
from typing import Annotated

from typer import Argument, Option, Typer

from src.csv import gen_csv
from src.meta import Base, gen_meta, get_base_id, get_base_meta_data
from src.python import gen_python
from src.typescript import gen_typescript

app = Typer()


@app.command()
def meta(
    folder: Annotated[str, Argument(help="Path to the output folder")],
):
    """Fetch Airtable metadata into a json file."""
    base_id = get_base_id()
    metadata = get_base_meta_data(base_id)
    folder_path = Path(folder)
    folder_path.mkdir(parents=True, exist_ok=True)
    gen_meta(metadata=metadata, folder=folder_path)


@app.command()
def csv(
    folder: Annotated[str, Argument(help="Path to the output folder")],
    fresh: Annotated[bool, Option(help="Generate fresh property names instead of using custom names if they exist.")] = False,
):
    """Export Airtable metadata to CSV format."""
    base_id = get_base_id()
    metadata = get_base_meta_data(base_id)
    folder_path = Path(folder)
    folder_path.mkdir(parents=True, exist_ok=True)
    base = Base.from_dict(metadata, base_id, csv_folder=folder_path)
    gen_csv(base=base, folder=folder_path, fresh=fresh)


@app.command()
def py(
    folder: Annotated[str, Argument(help="Path to the output folder")],
    csv_folder: Annotated[str, Option(help="Path to the folder containing the CSV generated by the `csv` command.")] = "",
    fresh: Annotated[bool, Option(help="Generate fresh property names instead of using custom names if they exist.")] = False,
    formulas: Annotated[bool, Option(help="Include formula-helper classes in the output.")] = True,
    wrappers: Annotated[bool, Option(help="Include wrapper classes for tables and base in the output.")] = True,
    package_prefix: Annotated[str, Option(help="Use if the code is not generated at the root level of the package")] = "",
):
    """Generate types and models in Python"""
    folder_path = Path(folder)
    folder_path.mkdir(parents=True, exist_ok=True)
    csv_folder_path = Path(csv_folder) if csv_folder else folder_path
    base_id = get_base_id()
    metadata = get_base_meta_data(base_id)
    base = Base.from_dict(metadata, base_id, csv_folder=csv_folder_path)
    if fresh:
        gen_csv(base=base, folder=csv_folder_path, fresh=True)
    gen_python(
        base=base,
        output_folder=folder_path,
        csv_folder=csv_folder_path,
        formulas=formulas,
        wrappers=wrappers,
        package_prefix=package_prefix,
    )


@app.command()
def ts(
    folder: Annotated[str, Argument(help="Path to the output folder")],
    csv_folder: Annotated[str, Option(help="Path to the folder containing the CSV generated by the `csv` command.")] = "",
    fresh: Annotated[bool, Option(help="Generate fresh property names instead of using custom names if they exist.")] = False,
):
    """Generate types and models in TypeScript"""
    folder_path = Path(folder)
    folder_path.mkdir(parents=True, exist_ok=True)
    csv_folder_path = Path(csv_folder) if csv_folder else folder_path
    base_id = get_base_id()
    metadata = get_base_meta_data(base_id)
    base = Base.from_dict(metadata, base_id, csv_folder=csv_folder_path)
    if fresh:
        gen_csv(base=base, folder=csv_folder_path, fresh=True)
    gen_typescript(base=base, output_folder=folder_path)


if __name__ == "__main__":
    from dotenv import load_dotenv

    load_dotenv()
    app()
