from pathlib import Path
from typing import Annotated

from rich import print
from typer import Argument, Option, Typer

from src.csv import generate_csv
from src.meta import Base, generate_meta, get_base_meta_data
from src.python import generate_python
from src.typescript import generate_typescript

app = Typer()


@app.command()
def meta(
    folder: Annotated[str, Argument(help="Path to the output folder")],
):
    """Fetch Airtable metadata into a json file."""
    metadata = get_base_meta_data()
    folder_path = Path(folder)
    folder_path.mkdir(parents=True, exist_ok=True)
    generate_meta(metadata=metadata, folder=folder_path)


@app.command()
def csv(
    folder: Annotated[str, Argument(help="Path to the output folder")],
    fresh: Annotated[bool, Option(help="Generate fresh property names instead of using custom names if they exist.")] = False,
):
    """Export Airtable metadata to CSV format."""
    folder_path = Path(folder)
    folder_path.mkdir(parents=True, exist_ok=True)
    base = Base.new(csv_folder=folder_path)
    generate_csv(base=base, folder=folder_path, fresh=fresh)


@app.command()
def py(
    folder: Annotated[str, Argument(help="Path to the output folder")],
    csv_folder: Annotated[str, Option(help="Path to the folder containing the CSV generated by the `csv` command.")] = "",
    fresh: Annotated[bool, Option(help="Generate fresh property names instead of using custom names if they exist.")] = False,
    formulas: Annotated[bool, Option(help="Include formula-helper classes in the output.")] = True,
    wrappers: Annotated[bool, Option(help="Include wrapper classes for tables and base in the output.")] = True,
    package_prefix: Annotated[str, Option(help="Use if the code is not generated at the root level of the package")] = "",
):
    """Generate types and models in Python"""
    folder_path = Path(folder)
    folder_path.mkdir(parents=True, exist_ok=True)
    csv_folder_path = Path(csv_folder) if csv_folder else folder_path
    base = Base.new(csv_folder=csv_folder_path)
    if fresh:
        generate_csv(base=base, folder=csv_folder_path, fresh=True)
    generate_python(
        base=base,
        output_folder=folder_path,
        csv_folder=csv_folder_path,
        formulas=formulas,
        wrappers=wrappers,
        package_prefix=package_prefix,
    )


@app.command()
def ts(
    folder: Annotated[str, Argument(help="Path to the output folder")],
    csv_folder: Annotated[str, Option(help="Path to the folder containing the CSV generated by the `csv` command.")] = "",
    fresh: Annotated[bool, Option(help="Generate fresh property names instead of using custom names if they exist.")] = False,
):
    """Generate types and models in TypeScript"""
    folder_path = Path(folder)
    folder_path.mkdir(parents=True, exist_ok=True)
    csv_folder_path = Path(csv_folder) if csv_folder else folder_path
    base = Base.new(csv_folder=csv_folder_path)
    if fresh:
        generate_csv(base=base, folder=csv_folder_path, fresh=True)
    generate_typescript(base=base, output_folder=folder_path)


@app.command()
def invalid():
    """Check for invalid fields"""
    base = Base.new()
    for table in base.tables:
        for field in table.fields:
            if not field.is_valid():
                print(f"[yellow]Invalid field:[/] Table '{table.name}', Field '{field.name}' ({field.id})")


if __name__ == "__main__":
    from dotenv import load_dotenv

    load_dotenv()
    app()
